In [18]:
from transformers import TFAutoModel, AutoTokenizer

!pip3 install datasets

from datasets import load_dataset

In [19]:
!pip3 freeze | grep datasets

datasets==2.21.0
tensorflow-datasets==4.9.6
vega-datasets==0.9.0


In [20]:
#importing bert
model = TFAutoModel.from_pretrained("bert-base-uncased")


Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFBertModel: ['cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.bias', 'cls.seq_relationship.weight', 'cls.predictions.bias', 'cls.predictions.transform.LayerNorm.bias']
- This IS expected if you are initializing TFBertModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFBertModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions w

In [21]:
#Raw data can't be fed into it so we tokenize the data
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")

In [22]:
#Example of how it tokanizes the data, token 101 and 102 represent special tokens start and end, tokens in middel represents Hi
#Attenton_mask is all 1 because there are no padding tokens

#Padding tokens: because the sent list or data might have variable sets of length

#truncation will truncate any text that has more them 512 words which is the maximum context size

#return_tensors will change a normal python list to a tensorflow tensor


inputs = tokenizer(['Prabhakar', 'How are you', 'I am fine'], padding=True, truncation=True, return_tensors='tf')
inputs

{'input_ids': <tf.Tensor: shape=(3, 6), dtype=int32, numpy=
array([[  101, 10975,  7875, 20459,  2906,   102],
       [  101,  2129,  2024,  2017,   102,     0],
       [  101,  1045,  2572,  2986,   102,     0]], dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(3, 6), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(3, 6), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1, 0]], dtype=int32)>}

In [23]:
output = model(inputs)
output

TFBaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=<tf.Tensor: shape=(3, 6, 768), dtype=float32, numpy=
array([[[-0.44375634,  0.04848439, -0.08849109, ..., -0.25273353,
          0.37711632,  0.2368927 ],
        [ 0.48516887, -0.5000743 , -0.9268864 , ...,  0.7223629 ,
          0.23470442, -0.14089698],
        [-0.34464   ,  0.3246554 , -0.5214517 , ...,  0.13185291,
         -0.33788028, -1.0134296 ],
        [ 0.02138753,  0.69334185, -0.5173495 , ...,  0.2531175 ,
          0.26947987, -0.24730566],
        [-0.17565571, -0.10682876, -0.21663895, ...,  0.11903352,
         -0.42963374, -0.99646723],
        [ 0.62714595, -0.0444914 , -0.12455191, ...,  0.03166486,
         -0.5084701 , -0.23661101]],

       [[ 0.07747278,  0.04501393, -0.16765119, ..., -0.3346344 ,
          0.16396365,  0.12080576],
        [-0.02718055, -0.71175593, -0.29173434, ..., -0.12723002,
          0.67878383, -0.5343533 ],
        [ 0.64420515, -0.98045266, -0.0380943 , ..., -0.6010785 

In [24]:
emotions = load_dataset('SetFit/emotion')

Repo card metadata block was not found. Setting CardData to empty.


In [25]:
emotions

DatasetDict({
    train: Dataset({
        features: ['text', 'label', 'label_text'],
        num_rows: 16000
    })
    validation: Dataset({
        features: ['text', 'label', 'label_text'],
        num_rows: 2000
    })
    test: Dataset({
        features: ['text', 'label', 'label_text'],
        num_rows: 2000
    })
})

In [26]:
def tokenize(batch):
  return tokenizer(batch["text"], padding=True, truncation=True)

In [27]:
emotions_encoded = emotions.map(tokenize, batched=True, batch_size=None)

Map:   0%|          | 0/16000 [00:00<?, ? examples/s]

Map:   0%|          | 0/2000 [00:00<?, ? examples/s]

Map:   0%|          | 0/2000 [00:00<?, ? examples/s]

In [28]:
emotions_encoded

DatasetDict({
    train: Dataset({
        features: ['text', 'label', 'label_text', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 16000
    })
    validation: Dataset({
        features: ['text', 'label', 'label_text', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 2000
    })
    test: Dataset({
        features: ['text', 'label', 'label_text', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 2000
    })
})